packages:
  - playground
  - docs-site

enableGlobalVirtualStore: false

overrides:
  h3: 1.15.11
  tailwindcss: 4.1.18

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
