/**
 * Vendors the Prism grammar registry that {@link ../src/runtime/components/ECodeBlock}
 * tokenizes with into a single self-contained module,
 * `src/runtime/components/code-block-prism.ts`.
 *
 * WHY: ECodeBlock used to build its registry at runtime with
 * `createRequire(import.meta.url)` + `require('prismjs/components/')` +
 * `loadLanguages()`. Inside a bundled Nitro production chunk `import.meta.url`
 * becomes the virtual `file:///_entry.js`, so `createRequire` resolves modules
 * from `/` and `require('prismjs')` throws `Cannot find module 'prismjs'` no
 * matter what the consumer installed. React Email dodges this by shipping a
 * fully-preloaded, statically-imported grammar dump
 * (`packages/react-email/src/components/code-block/prism.ts`). We do the same,
 * but generated byte-reproducibly from the pinned `prismjs` package instead of
 * hand-maintained.
 *
 * HOW: `loadLanguages()` with no arguments loads every grammar in the
 * dependency order computed by prismjs' own `getLoader`, deleting and reloading
 * each one so the preloaded `prism.js` set is rebuilt from scratch. We reuse
 * that exact resolver here to obtain the identical order, then inline each
 * `components/prism-<id>.js` source verbatim — each wrapped in an IIFE that
 * receives the shared `Prism` (the grammars reference a free `Prism` global) so
 * per-file top-level declarations cannot collide. The result registers the same
 * grammars, in the same order, with NO `require` / `createRequire` / dynamic
 * `import`, so it bundles into a static chunk.
 *
 * Run this once whenever the pinned `prismjs` version changes:
 *
 *   node --import tsx scripts/vendor-prism.ts
 *
 * The byte-for-byte reproducibility guard lives in
 * test/unit/code-block/prism-registry.test.ts (the "prism:vendor-check"
 * behavior), mirroring `oracle:check` and the Tailwind stylesheet guard.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const require = createRequire(import.meta.url)
const scriptDir = dirname(fileURLToPath(import.meta.url))

/** Resolve the installed prismjs package root from its package.json. */
const prismPkgRoot = dirname(require.resolve('prismjs/package.json'))

interface ComponentEntry {
  alias?: string | string[]
}
interface Components {
  languages: Record<string, ComponentEntry | string>
}
type GetLoader = (
  components: Components,
  load: string[],
  loaded?: string[],
) => { load: (callback: (id: string) => void) => void }

/**
 * The exact grammar load order `loadLanguages()` uses: prismjs' own dependency
 * resolver over every language id, starting from an empty loaded set (the
 * runtime deletes and reloads even the preloaded grammars, so the effective
 * order is the full topological one).
 */
export function resolvePrismLoadOrder(): string[] {
  const components = require('prismjs/components.js') as Components
  const getLoader = require('prismjs/dependencies.js') as GetLoader
  const languageIds = Object.keys(components.languages).filter(id => id !== 'meta')
  const order: string[] = []
  getLoader(components, languageIds, []).load(id => order.push(id))
  return order
}

/** Build the full source of the vendored `code-block-prism.ts` module. */
export function buildPrismModuleSource(): string {
  const prismVersion = (
    JSON.parse(readFileSync(join(prismPkgRoot, 'package.json'), 'utf8')) as { version: string }
  ).version

  const banner = `// AUTO-GENERATED by scripts/vendor-prism.ts — DO NOT EDIT BY HAND.
// The full Prism grammar registry, vendored from the installed \`prismjs\` package
// (prismjs@${prismVersion}) in the exact dependency order \`loadLanguages()\` uses,
// with NO require/createRequire/dynamic import so it bundles into a static chunk.
// Regenerate with: node --import tsx scripts/vendor-prism.ts
// The byte-for-byte guard lives in test/unit/code-block/prism-registry.test.ts.
`

  const header = `// @ts-nocheck
import * as PrismImport from 'prismjs'

// prismjs is CommonJS; the default export is the Prism namespace under ESM
// interop, and the module object itself under some bundlers. Normalize both.
const Prism = (PrismImport.default ?? PrismImport) as typeof import('prismjs')

export { Prism }
`

  const grammars = resolvePrismLoadOrder().map((id) => {
    const source = readFileSync(join(prismPkgRoot, 'components', `prism-${id}.js`), 'utf8').replace(/\s+$/, '')
    // Each grammar file mutates a free \`Prism\` global; pass it in as a parameter
    // so the reference binds explicitly and per-file top-level vars stay scoped.
    return `// ---- prism-${id} ----\n;(function (Prism) {\n${source}\n})(Prism)`
  }).join('\n\n')

  return `${banner}\n${header}\n${grammars}\n`
}

const OUTPUT_PATH = join(scriptDir, '..', 'src/runtime/components/code-block-prism.ts')

function main(): void {
  writeFileSync(OUTPUT_PATH, buildPrismModuleSource(), 'utf8')
  console.log(`Wrote ${OUTPUT_PATH}`)
}

const invokedPath = process.argv[1]
if (invokedPath && import.meta.url === pathToFileURL(invokedPath).href) {
  main()
}
