/**
 * Vendors the bundled Tailwind CSS v4 stylesheets that drive the email engine's
 * `compile()` call into a single string-export module.
 *
 * React Email (`@react-email/render` / `react-email@6.9.0`) ships its own
 * hand-maintained copies of these stylesheets under
 * `components/tailwind/utils/tailwindcss/tailwind-stylesheets/*.ts`. Those copies
 * differ from the installed `tailwindcss` package ONLY inside CSS comments
 * (e.g. `` `:invalid` `` -> `` `: invalid` ``); the css-tree parser drops
 * comments before any rule is extracted, so the two are functionally identical.
 *
 * We deliberately vendor byte-for-byte from the installed `tailwindcss` package
 * instead of hand-copying, so the source of truth is the pinned dependency and a
 * test can assert reproducibility (mirroring `oracle:check`). Run this script
 * once whenever the pinned `tailwindcss` version changes:
 *
 *   node --import tsx scripts/vendor-tailwind-css.ts
 *
 * The reproducibility guard lives in test/unit/tailwind/stylesheets.test.ts
 * (the "tailwind:vendor-check" behavior), not in package.json.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const scriptDir = dirname(fileURLToPath(import.meta.url))

/** Resolve the installed tailwindcss package root from its package.json. */
const tailwindPkgRoot = dirname(require.resolve('tailwindcss/package.json'))

/** id -> [source css filename, exported constant name] */
const SOURCES = [
  ['index.css', 'indexCss'],
  ['preflight.css', 'preflightCss'],
  ['theme.css', 'themeCss'],
  ['utilities.css', 'utilitiesCss'],
] as const

/** Escape a raw string so it round-trips through a JS template literal verbatim. */
function toTemplateLiteral(raw: string): string {
  const escaped = raw
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
  return `\`${escaped}\``
}

const OUTPUT_PATH = join(scriptDir, '..', 'src/runtime/tailwind/engine/stylesheets.ts')

function main(): void {
  const banner = `// AUTO-GENERATED by scripts/vendor-tailwind-css.ts — DO NOT EDIT BY HAND.
// Vendored byte-for-byte from the installed \`tailwindcss\` package
// (tailwindcss@${JSON.parse(readFileSync(join(tailwindPkgRoot, 'package.json'), 'utf8')).version}).
// Regenerate with: node --import tsx scripts/vendor-tailwind-css.ts
// The byte-for-byte guard lives in test/unit/tailwind/stylesheets.test.ts.
`

  const body = SOURCES.map(([file, name]) => {
    const content = readFileSync(join(tailwindPkgRoot, file), 'utf8')
    return `export const ${name} = ${toTemplateLiteral(content)}`
  }).join('\n\n')

  writeFileSync(OUTPUT_PATH, `${banner}\n${body}\n`, 'utf8')

  console.log(`Wrote ${OUTPUT_PATH}`)
}

main()
