import { execFile } from 'node:child_process'
import { lstat, mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { promisify } from 'node:util'
import { build } from 'esbuild'
import ts from 'typescript'
import { discoverEmailTemplates } from './template-registry/discovery'
import { generateEmailRegistry, generateEmailTypes } from './template-registry/generation'
import { emailTemplatesPlugin } from './build/compile-template'

const execute = promisify(execFile)
const require = createRequire(import.meta.url)
const renderImport = '@lupinum/nuxt-email/render'
const ownershipMarker = '.nuxt-email-generated'
const ownershipContent = 'Generated by @lupinum/nuxt-email/build. Do not edit.\n'

export interface BuildEmailRegistryOptions {
  /** Application/project root, without loading its Nuxt configuration. */
  rootDir: string
  /** Template directory relative to rootDir. Defaults to app/emails. */
  templatesDir?: string
  /** Dedicated directory inside rootDir. Must be absent or previously created by this helper. */
  outDir: string
}

function contains(parent: string, child: string): boolean {
  const path = relative(parent, child)
  return path === '' || (!path.startsWith(`..`) && !isAbsolute(path))
}

async function replaceOutputDirectory(
  staging: string,
  outDir: string,
  replaceOutput: boolean,
): Promise<void> {
  const previousRoot = await mkdtemp(join(dirname(outDir), '.nuxt-email-previous-'))
  const previous = join(previousRoot, 'output')
  try {
    if (replaceOutput) await rename(outDir, previous)
    try {
      await rename(staging, outDir)
    }
    catch (error) {
      if (replaceOutput) await rename(previous, outDir)
      throw error
    }
  }
  finally {
    await rm(previousRoot, { recursive: true, force: true })
  }
}

async function normalizeDeclarationImports(directory: string): Promise<void> {
  for (const file of await readdir(directory, { recursive: true })) {
    if (!/\.d\.[cm]?ts$/.test(file)) continue
    const path = join(directory, file)
    const source = ts.createSourceFile(path, await readFile(path, 'utf8'), ts.ScriptTarget.Latest, true)
    const transformed = ts.transform(source, [(context) => {
      const visit: ts.Visitor = (node) => {
        if (ts.isStringLiteral(node) && node.text.startsWith('.')) {
          const parent = node.parent
          const isImport = ts.isImportDeclaration(parent) || ts.isExportDeclaration(parent)
            || (ts.isLiteralTypeNode(parent) && ts.isImportTypeNode(parent.parent))
          if (isImport && !node.text.endsWith('.json')) {
            const module = ts.resolveModuleName(node.text, path, { moduleResolution: ts.ModuleResolutionKind.Bundler }, ts.sys).resolvedModule
            if (!module) throw new Error(`Cannot resolve emitted declaration import ${JSON.stringify(node.text)} from ${path}. Keep local imports inside the email directory.`)
            const target = relative(dirname(path), module.resolvedFileName).replaceAll('\\', '/').replace(/\.d\.([cm]?)ts$/, '.$1js')
            return ts.factory.createStringLiteral(target.startsWith('.') ? target : `./${target}`)
          }
        }
        return ts.visitEachChild(node, visit, context)
      }
      return node => ts.visitNode(node, visit) as ts.SourceFile
    }])
    try {
      await writeFile(path, ts.createPrinter().printFile(transformed.transformed[0]!))
    }
    finally {
      transformed.dispose()
    }
  }
}

/** Compile trusted application templates. Never call this from a request or action. */
export async function buildEmailRegistry(options: BuildEmailRegistryOptions): Promise<void> {
  if (Object.keys(options).some(key => key !== 'rootDir' && key !== 'outDir' && key !== 'templatesDir')) {
    throw new TypeError('buildEmailRegistry accepts only rootDir, outDir and templatesDir.')
  }
  const rootDir = resolve(options.rootDir)
  const templatesDir = options.templatesDir ?? 'app/emails'
  if (isAbsolute(templatesDir)) throw new TypeError('templatesDir must be relative to rootDir.')
  const directory = resolve(rootDir, templatesDir)
  if (!contains(rootDir, directory)) throw new TypeError('templatesDir must remain inside rootDir.')
  const outDir = resolve(rootDir, options.outDir)
  if (!contains(rootDir, outDir)) throw new TypeError('outDir must remain inside rootDir so the generated module can resolve project dependencies.')
  if (contains(directory, outDir) || contains(outDir, directory)) {
    throw new TypeError('Generated output must be outside and must not contain the email directory.')
  }
  let replaceOutput = false
  try {
    const output = await lstat(outDir)
    if (!output.isDirectory() || output.isSymbolicLink()) throw new TypeError('outDir must be a generated directory, not a file or symlink.')
    const marker = await readFile(join(outDir, ownershipMarker), 'utf8').catch(() => '')
    if (marker !== ownershipContent) throw new TypeError('Refusing to replace an outDir not owned by this build.')
    replaceOutput = true
  }
  catch (error) {
    if (!(error instanceof Error && 'code' in error && error.code === 'ENOENT')) throw error
  }
  const templates = await discoverEmailTemplates(directory)
  if (templates.length === 0) throw new TypeError('The email directory contains no templates.')

  await mkdir(dirname(outDir), { recursive: true })
  const staging = await mkdtemp(join(dirname(outDir), '.nuxt-email-build-'))
  try {
    const declarations = join(staging, 'types')
    const globals = join(staging, 'components.d.ts')
    await writeFile(globals, `import type { EmailComponents } from '${renderImport}'\ndeclare module 'vue' { interface GlobalComponents extends EmailComponents {} }\nexport {}\n`)
    const config = join(staging, 'tsconfig.json')
    await writeFile(config, JSON.stringify({
      compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler',
        strict: true, skipLibCheck: true, declaration: true, emitDeclarationOnly: true,
        noEmitOnError: true, rootDir: directory, declarationDir: declarations,
        types: [], lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      },
      vueCompilerOptions: { strictTemplates: true },
      files: [globals, ...templates.map(template => template.sourcePath)],
    }))
    try {
      await execute(process.execPath, [require.resolve('vue-tsc/bin/vue-tsc.js'), '-p', config], {
        cwd: directory, maxBuffer: 4 * 1024 * 1024,
      })
    }
    catch (error) {
      const diagnostics = error instanceof Error && 'stdout' in error && typeof error.stdout === 'string'
        ? error.stdout.trim()
        : ''
      throw new Error(`Email declaration build failed${diagnostics ? `:\n${diagnostics}` : '.'}`, { cause: error })
    }
    await normalizeDeclarationImports(declarations)

    const registry = generateEmailRegistry(templates, {
      emailRenderError: renderImport,
      renderEmailComponent: renderImport,
      templateRegistryErrors: renderImport,
    })
    await build({
      absWorkingDir: rootDir,
      tsconfigRaw: { compilerOptions: { target: 'ES2022', module: 'ESNext' } },
      stdin: { contents: registry, resolveDir: directory, sourcefile: 'email-registry.js' },
      outfile: join(staging, 'index.mjs'),
      bundle: true, format: 'esm', platform: 'node', target: 'node22',
      packages: 'external', logLevel: 'silent', plugins: [emailTemplatesPlugin(directory)],
    })
    await writeFile(join(staging, 'index.d.mts'), generateEmailTypes(
      templates.map(template => ({
        name: template.name,
        sourcePath: `./types/${template.name}.vue.js`,
      })),
      { renderedEmail: renderImport },
    ))
    await writeFile(join(staging, ownershipMarker), ownershipContent)
    await rm(config)
    await rm(globals)

    // Only replace a directory previously created by this helper. Compilation
    // failures leave the last successful output untouched.
    await replaceOutputDirectory(staging, outDir, replaceOutput)
  }
  finally {
    await rm(staging, { recursive: true, force: true })
  }
}
